x -> scl: Federate
scl.link: layers.x

database {
   shape: image
   icon: https://icons.terrastruct.com/dev%2Fsafari.svg
}

backend {
   shape: image
   icon: https://img.icons8.com/color/96/spring-logo.png
}

x: Login {
   shape: cloud
   link: https://www.google.com
}




