direction: right
start: Start
process: Process
finish: Done

start -> process -> finish

layers: {
  detail: {
    direction: right
    process: Process
    validate: Validate
    store: Store
    process -> validate -> store
  }
}
